### Get Request
GET http://localhost:3000/users/

### POST REQUEST

POST http://localhost:3000/users/
Content-Type: application/json

{  
   "firstName": "John",
   "lastName": "Smith",
   "email": "assssfsafsdfaadsfafdf@gmail.com"
}


### Get user
GET http://localhost:3000/users/5f6a038b4b4b7e70c638d0b1


### PUT user
PUT http://localhost:3000/users/5f6a038b4b4b7e70c638d0b1
Content-Type: application/json

{  
   "firstName": "Josadfdahn1234",
   "lastName": "Smitfasfdh",
   "email": "assssfsasdfaafsdfaadsfafdf@gmail.com"
}


### PUT user
PATCH  http://localhost:3000/users/5f6a038b4b4b7e70c638d0b1
Content-Type: application/json

{  
   "firstName": "walladsfadal"
}

### DELELTE user
DELETE  http://localhost:3000/users/5f6a038b4b4b7e70c638d0b2



### Get Request
GET http://localhost:3000/users/5f6a0412b016b47275ab5fdc/cars/


### POST Request
POST http://localhost:3000/users/5f6a0412b016b47275ab5fdc/cars
Content-Type: application/json

{  
   "make": "Toyota",
   "model": "Prius",
   "year": 2015
}